### ISSUE TITLE
Usage of @types in dependencies

### ISSUE THREAD

**Issue by olehcambel** [joshuaslate/type-cacheable#110]
Actually, do we need types like `@types/redis`, `@types/ioredis`, `@types/node-cache` in dependencies of package.json? I mean, when users install your lib they also install appropriate lib for caching with its own types.

I can make PR later.

**Comment by joshuaslate** [comment]
I thought that originally too, but ran into issues, which is why I added these as regular dependencies to begin with.

One solution might be to use a tool like Lerna to publish the adapters separately. Something like:

```
@type-cacheable/core
@type-cacheable/node-redis
@type-cacheable/io-redis
@type-cachable/node-cache
```

Then the consumer is only getting what they need.

**Comment by olehcambel** [comment]
hmm, I don't know. For example I got this message on `npm i`

> npm WARN deprecated @types/node-cache@4.2.5: This is a stub types definition. node-cache provides its own type definitions, so you do not need this installed.

**Comment by joshuaslate** [comment]
Hi Oleh, please try with the latest version, v5.0.1 and let me know if there are any issues. Note that the npm packages have been changed to:

```
@type-cacheable/core
@type-cacheable/redis-adapter
@type-cacheable/ioredis-adapter
@type-cachable/node-cache-adapter
```

You will need `@type-cacheable/core` and whichever corresponding adapter, then simply update your imports and things should work as in the latest v4 release otherwise.
