### ISSUE TITLE
[bug] ttlseconds is actually using milliseconds and not seconds

### ISSUE THREAD

**Issue by paulfrench** [joshuaslate/type-cacheable#304]
No idea if this is a core bug or the lrucache adaptor bug.

I'm using LRUCache. When specifying ttlseconds I have to actually specify millis. e.g for 30 seconds I have to specify

ttlseconds: 30000

It took me a while to work out why caching wasn't working!

**Comment by joshuaslate** [comment]
This is resolved in v9.0.1.

**Comment by paulfrench** [comment]
Hello, I retested with 9.0.1

    "@type-cacheable/core": "^9.0.1",
    "@type-cacheable/lru-cache-adapter": "^9.0.1",

Still needed to multiply all ttlseconds by 1000

**Comment by Wazbat** [comment]
I'm a little confused, is this still an existing bug? Or is this resolved now?

**Comment by joshuaslate** [comment]
@Wazbat, I just tested locally and it seems to be working fine for me. Are you still seeing the issue?

When passing the `ttlSeconds` option with a value of `30` to `@Cacheable()`, I see the LRU cache internally gives it a TTL of `30000` ms. When you pass `ttl` to the `LRUCache()` constructor directly, that needs to be in ms, because that's the unit that the lru-cache library expects.

I don't use this adapter, personally, but I'm happy to help solve any issue you may be seeing with it.

**Comment by Wazbat** [comment]
Ahh, I just tried it myself and I'm not seeing any issue. It appears to behave correctly when set to "60" for me, I assume for other values too.

I was just a little confused as I saw the issue was still open and wasn't sure if it was a problem that was still live
